#!/bin/bash

# Set up a fresh amazon AMI to run docker/jenkins.

# install Jenkins and Java 8  
sudo yum update -y
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum install jenkins -y
sudo yum install -y java-1.8.0-openjdk.x86_64
sudo /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
sudo /usr/sbin/alternatives --set javac /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/javac
sudo yum remove java-1.7
sudo service jenkins start

# install git
sudo yum install -y git 

# install docker and add jenkins to group docker
sudo yum install -y docker
sudo service docker start
sudo usermod -aG docker jenkins

# test docker installation 
#hello=$(docker run hello-world | awk 'FNR==2{print $1;}')
#
#if [[ $hello == "Hello" ]]; then 
#    echo "Successfully installed docker. Logout to apply group permissions to run without sudo"; 
#else
# echo "Failed executing command docker run hello-world"; 
#fi

# reboot may be needed
# reboot
